# Generated by Django 6.0.1 on 2026-03-29 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('projects', '0001_initial'),
        ('textes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='longProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('public_profile', models.BooleanField(default=True)),
                ('favourites_projects', models.ManyToManyField(blank=True, related_name='favorited_by', to='projects.projects')),
                ('favourites_textes', models.ManyToManyField(blank=True, related_name='favorited_by', to='textes.text')),
                ('followed_users', models.ManyToManyField(blank=True, related_name='followers', to='users.longprofile')),
                ('following_users', models.ManyToManyField(blank=True, related_name='following', to='users.longprofile')),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to='users.longprofile')),
                ('short_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended_profile', to='main.shortprofile')),
            ],
        ),
    ]
