# Generated by Django 6.0.1 on 2026-03-02 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_per_chapter', models.IntegerField(default=10)),
                ('chapters', models.IntegerField(default=1)),
                ('views', models.IntegerField(default=0)),
                ('favorites_count', models.IntegerField(default=0)),
                ('authors', models.ManyToManyField(blank=True, related_name='authored_texts', to=settings.AUTH_USER_MODEL)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorite_texts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
