# Generated by Django 6.0.1 on 2026-03-11 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='authors',
            field=models.ManyToManyField(editable=False, related_name='authored_texts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='text',
            name='favorites',
            field=models.ManyToManyField(editable=False, related_name='favorite_texts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='text',
            name='views',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
