# Generated by Django 5.2.7 on 2025-10-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Short_Description', models.CharField(max_length=500)),
                ('Description', models.TextField()),
                ('Image', models.ImageField(upload_to='project_images/')),
                ('Is_Public', models.BooleanField(default=True)),
                ('Is_Completed', models.BooleanField(default=False)),
            ],
        ),
    ]
