# Generated by Django 6.0.1 on 2026-02-28 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Short_Description', models.CharField(max_length=500)),
                ('Description', models.TextField()),
                ('Image', models.ImageField(upload_to='project_images/')),
                ('Is_Public', models.BooleanField(default=True)),
                ('Is_Completed', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('favorites_count', models.IntegerField(default=0)),
                ('Favorites', models.ManyToManyField(blank=True, related_name='favorite_projects', to=settings.AUTH_USER_MODEL)),
                ('authors', models.ManyToManyField(blank=True, related_name='authored_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
